// Stardew villagers - birthdays + loved gifts (parsed from the wiki). Portraits: images/npc_<key>.png
const NPCS = [
  { key:"abigail", name:"Abigail", birthday:{ season:"Fall", day:13 }, loves:["Amethyst","Banana Pudding","Blackberry Cobbler","Chocolate Cake","Monster Compendium","Pufferfish","Pumpkin","Spicy Eel"] },
  { key:"alex", name:"Alex", birthday:{ season:"Summer", day:13 }, loves:["Complete Breakfast","Jack Be Nimble, Jack Be Thick","Salmon Dinner"] },
  { key:"caroline", name:"Caroline", birthday:{ season:"Winter", day:7 }, loves:["Fish Taco","Green Tea","Summer Spangle","Tropical Curry"] },
  { key:"clint", name:"Clint", birthday:{ season:"Winter", day:26 }, loves:["Amethyst","Aquamarine","Artichoke Dip","Emerald","Fiddlehead Risotto","Gold Bar","Iridium Bar","Jade","Omni Geode","Ruby","Topaz"] },
  { key:"demetrius", name:"Demetrius", birthday:{ season:"Summer", day:19 }, loves:["Bean Hotpot","Ice Cream","Rice Pudding","Strawberry"] },
  { key:"dwarf", name:"Dwarf", birthday:{ season:"Summer", day:22 }, loves:["Amethyst","Aquamarine","Emerald","Jade","Lava Eel","Lemon Stone","Omni Geode","Ruby","Topaz"] },
  { key:"elliott", name:"Elliott", birthday:{ season:"Fall", day:5 }, loves:["Crab Cakes","Duck Feather","Lobster","Pomegranate","Squid Ink","Tom Kha Soup"] },
  { key:"emily", name:"Emily", birthday:{ season:"Spring", day:27 }, loves:["Amethyst","Aquamarine","Cloth","Emerald","Jade","Parrot Egg","Ruby","Survival Burger","Topaz","Wool"] },
  { key:"evelyn", name:"Evelyn", birthday:{ season:"Winter", day:20 }, loves:["Beet","Chocolate Cake","Diamond","Fairy Rose","Raisins","Stuffing","Tulip"] },
  { key:"george", name:"George", birthday:{ season:"Fall", day:24 }, loves:["Fried Mushroom","Leek"] },
  { key:"gus", name:"Gus", birthday:{ season:"Summer", day:8 }, loves:["Diamond","Escargot","Fish Taco","Orange","Tropical Curry"] },
  { key:"haley", name:"Haley", birthday:{ season:"Spring", day:14 }, loves:["Coconut","Fruit Salad","Pink Cake","Sunflower"] },
  { key:"harvey", name:"Harvey", birthday:{ season:"Winter", day:14 }, loves:["Coffee","Pickles","Super Meal","Truffle Oil","Wine"] },
  { key:"jas", name:"Jas", birthday:{ season:"Summer", day:4 }, loves:["Ancient Doll","Fairy Box","Fairy Rose","Pink Cake","Plum Pudding","Strange Doll (green)","Strange Doll (yellow)"] },
  { key:"jodi", name:"Jodi", birthday:{ season:"Fall", day:11 }, loves:["Chocolate Cake","Crispy Bass","Diamond","Eggplant Parmesan","Fried Eel","Pancakes","Rhubarb Pie","Vegetable Medley"] },
  { key:"kent", name:"Kent", birthday:{ season:"Spring", day:4 }, loves:["Fiddlehead Risotto","Roasted Hazelnuts"] },
  { key:"krobus", name:"Krobus", birthday:{ season:"Winter", day:1 }, loves:["Diamond","Iridium Bar","Monster Compendium","Monster Musk","Pumpkin","Void Egg","Void Mayonnaise","Wild Horseradish"] },
  { key:"leah", name:"Leah", birthday:{ season:"Winter", day:23 }, loves:["Goat Cheese","Poppyseed Muffin","Salad","Stir Fry","Truffle","Vegetable Medley","Wine"] },
  { key:"leo", name:"Leo", birthday:{ season:"Summer", day:26 }, loves:["Duck Feather","Mango","Ostrich Egg","Parrot Egg","Poi"] },
  { key:"lewis", name:"Lewis", birthday:{ season:"Spring", day:7 }, loves:["Autumn's Bounty","Glazed Yams","Green Tea","Hot Pepper","Vegetable Medley"] },
  { key:"linus", name:"Linus", birthday:{ season:"Winter", day:3 }, loves:["Blueberry Tart","Cactus Fruit","Coconut","Dish O' The Sea","The Alleyway Buffet","Yam"] },
  { key:"marnie", name:"Marnie", birthday:{ season:"Fall", day:18 }, loves:["Diamond","Farmer's Lunch","Pink Cake","Pumpkin Pie"] },
  { key:"maru", name:"Maru", birthday:{ season:"Summer", day:10 }, loves:["Battery Pack","Cauliflower","Cheese Cauliflower","Diamond","Dwarf Gadget","Gold Bar","Iridium Bar","Miner's Treat","Pepper Poppers","Radioactive Bar","Rhubarb Pie","Strawberry"] },
  { key:"pam", name:"Pam", birthday:{ season:"Spring", day:18 }, loves:["Beer","Cactus Fruit","Glazed Yams","Mead","Pale Ale","Parsnip","Parsnip Soup","Piña Colada"] },
  { key:"penny", name:"Penny", birthday:{ season:"Fall", day:2 }, loves:["Diamond","Emerald","Melon","Poppy","Poppyseed Muffin","Red Plate","Roots Platter","Sandfish","Tom Kha Soup"] },
  { key:"pierre", name:"Pierre", birthday:{ season:"Spring", day:26 }, loves:["Fried Calamari","Price Catalogue"] },
  { key:"robin", name:"Robin", birthday:{ season:"Fall", day:21 }, loves:["Goat Cheese","Peach","Spaghetti","Woody's Secret"] },
  { key:"sam", name:"Sam", birthday:{ season:"Summer", day:17 }, loves:["Cactus Fruit","Maple_Bar","Tigerseye"] },
  { key:"sandy", name:"Sandy", birthday:{ season:"Fall", day:15 }, loves:["Crocus","Daffodil","Mango Sticky Rice","Sweet Pea"] },
  { key:"sebastian", name:"Sebastian", birthday:{ season:"Winter", day:10 }, loves:["Green Frog Egg","Frozen Tear","Obsidian","Pumpkin Soup","Sashimi","Fish","Void Egg"] },
  { key:"shane", name:"Shane", birthday:{ season:"Spring", day:20 }, loves:["Beer","Hot Pepper","Pepper Poppers","Pizza"] },
  { key:"vincent", name:"Vincent", birthday:{ season:"Spring", day:10 }, loves:["Cranberry Candy","Green Frog Egg","Ginger Ale","Grape","Pink Cake","Snail"] },
  { key:"willy", name:"Willy", birthday:{ season:"Summer", day:24 }, loves:["Catfish","Diamond","Gold Bar","Iridium Bar","Jewels Of The Sea","Mead","Octopus","Pumpkin","Sea Cucumber","Sturgeon","The Art O' Crabbing"] },
  { key:"wizard", name:"Wizard", birthday:{ season:"Winter", day:17 }, loves:["Book of Mysteries","Purple Mushroom","Solar Essence","Super Cucumber","Void Essence"] },
];
